// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGRpgiCzyzHbcNWgY2PcU4boEVA22gcM',
    appId: '1:997915460525:android:59391767a4925bc86a1724',
    messagingSenderId: '997915460525',
    projectId: 'money-tally-gordonbowles',
    storageBucket: 'money-tally-gordonbowles.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcdb4h_pW7YfQ5dr2_w8GzE-iWL_g5vAw',
    appId: '1:997915460525:ios:58dca8d7740e64af6a1724',
    messagingSenderId: '997915460525',
    projectId: 'money-tally-gordonbowles',
    storageBucket: 'money-tally-gordonbowles.firebasestorage.app',
    iosBundleId: 'com.gordonbowles.moneytally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcdb4h_pW7YfQ5dr2_w8GzE-iWL_g5vAw',
    appId: '1:997915460525:ios:58dca8d7740e64af6a1724',
    messagingSenderId: '997915460525',
    projectId: 'money-tally-gordonbowles',
    storageBucket: 'money-tally-gordonbowles.firebasestorage.app',
    iosBundleId: 'com.gordonbowles.moneytally',
  );
}
